In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler # do not use the function Normalise() - it does something entirely different
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
df = pd.read_csv("fifa21_train.csv")
pd.set_option('display.max_columns', None)

df.head()

,ID,Name,Age,Nationality,Club,BP,Position,Team & Contract,Height,Weight,foot,Growth,Joined,Loan Date End,Value,Wage,Release Clause,Contract,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,184383,A. Pasche,26,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,Right,1,"Jul 1, 2015",NaN,€525K,€4K,€801K,2015 ~ 2020,258,54,47,43,70,44.0,286,61,44.0,55,63,63,346,64,73,61.0,66,82.0,306,62,73.0,71,55,45,290,54,52.0,62.0,68.0,54,54.0,148,49,56,43.0,48,7,12,14,9,6,1682,357,4 ★,2★,High,Medium,1 ★,69,51,63,63,51,60,3,58+1,58+1,58+1,61+0,62+0,62+0,62+0,61+0,63+1,63+1,63+1,63+1,63+1,63+1,63+1,63+1,59+1,59+1,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,188044,Alan Carvalho,30,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,Right,0,"Jan 16, 2015","Dec 31, 2020",€8.5M,€23K,€0,"Dec 31, 2020 On Loan",365,66,79,76,68,76.0,375,83,78.0,72,63,79,404,83,83,88.0,75,75.0,372,74,81.0,75,74,68,313,54,33.0,78.0,72.0,76,70.0,77,35,20,22.0,55,11,7,14,7,16,1961,412,3 ★,4★,High,Low,2 ★,83,75,68,82,33,71,44,77+0,77+0,77+0,77+0,77+0,77+0,77+0,77+0,76+1,76+1,76+1,76+1,68+2,68+2,68+2,76+1,57+2,53+2,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,184431,S. Giovinco,33,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,"5'4""",134lbs,Right,0,"Jan 31, 2019",NaN,€9M,€49K,€15.3M,2019 ~ 2022,336,73,76,34,78,75.0,424,85,89.0,91,74,85,424,84,76,93.0,78,93.0,308,79,34.0,75,42,78,332,75,26.0,80.0,78.0,73,82.0,80,23,29,28.0,21,6,3,6,3,3,1925,404,4 ★,4★,High,Medium,2 ★,80,77,78,86,27,56,73,73+2,73+2,73+2,80+0,79+0,79+0,79+0,80+0,80+0,80+0,80+0,79+1,74+2,74+2,74+2,79+1,59+2,56+2,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,233796,J. Evans,22,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,"5'10""",152lbs,Right,13,"Jul 1, 2016",NaN,€275K,€4K,€694K,2016 ~ 2021,242,44,42,58,62,36.0,259,54,41.0,46,57,61,282,54,59,59.0,55,55.0,277,57,60.0,64,58,38,257,61,57.0,31.0,54.0,54,48.0,168,55,58,55.0,42,8,9,6,7,12,1527,329,2 ★,2★,Medium,Medium,1 ★,57,44,54,57,57,60,7,50+2,50+2,50+2,51+0,51+0,51+0,51+0,51+0,53+2,53+2,53+2,53+2,56+2,56+2,56+2,53+2,56+2,58+2,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,234799,Y. Demoncy,23,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",150lbs,Right,8,"Jul 1, 2018",NaN,€725K,€2K,€1.4M,2018 ~ 2021,249,49,37,61,68,34.0,280,64,44.0,45,61,66,324,66,66,61.0,62,69.0,280,61,34.0,81,61,43,294,66,60.0,55.0,64.0,49,58.0,185,58,61,66.0,52,8,9,15,5,15,1664,360,2 ★,3★,Low,Medium,1 ★,66,44,60,64,60,66,4,56+2,56+2,56+2,59+0,59+0,59+0,59+0,59+0,61+2,61+2,61+2,62+2,63+2,63+2,63+2,62+2,64+2,64+2,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65

In [2]:
df.describe(include = "all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ID,11701.0,NaN,NaN,NaN,219436.649004,37480.006004,27.0,204060.0,229040.0,244176.0,259090.0
Name,11701,11232,J. Rojas,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,11701.0,NaN,NaN,NaN,25.27049,4.95764,16.0,21.0,25.0,29.0,43.0
Nationality,11701,159,England,1162,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Club,11683,885,OGC Nice,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
CB,11701,313,63+2,300,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RCB,11701,313,63+2,300,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RB,11701,262,62+2,387,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GK,11701,155,16+2,2157,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OVA,11701.0,NaN,NaN,NaN,66.921972,6.876081,38.0,62.0,67.0,72.0,93.0

In [3]:
df.dtypes

ID              int64
Name           object
Age             int64
Nationality    object
Club           object
                ...
CB             object
RCB            object
RB             object
GK             object
OVA             int64
Length: 101, dtype: object

In [4]:
df.columns.values

array(['ID', 'Name', 'Age', 'Nationality', 'Club', 'BP', 'Position',
       'Team & Contract', 'Height', 'Weight', 'foot', 'Growth', 'Joined',
       'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Contract',
       'Attacking', 'Crossing', 'Finishing', 'Heading Accuracy',
       'Short Passing', 'Volleys', 'Skill', 'Dribbling', 'Curve',
       'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength',
       'Long Shots', 'Mentality', 'Aggression', 'Interceptions',
       'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending',
       'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W',
       'D/W', 'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits',
       'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM',
       'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM',
       'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'GK', 'OVA'], dtype=object)

In [5]:
data2 = df.drop(["Name", "Nationality", "Club", "Position", "Joined", "Loan Date End", "Wage" , "Release Clause", "GK Diving", "GK Handling" , "GK Kicking", "GK Positioning", "GK Reflexes"], axis = 1)

In [6]:
data2.head()

,ID,Age,BP,Team & Contract,Height,Weight,foot,Growth,Value,Contract,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,184383,26,CM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,Right,1,€525K,2015 ~ 2020,258,54,47,43,70,44.0,286,61,44.0,55,63,63,346,64,73,61.0,66,82.0,306,62,73.0,71,55,45,290,54,52.0,62.0,68.0,54,54.0,148,49,56,43.0,48,1682,357,4 ★,2★,High,Medium,1 ★,69,51,63,63,51,60,3,58+1,58+1,58+1,61+0,62+0,62+0,62+0,61+0,63+1,63+1,63+1,63+1,63+1,63+1,63+1,63+1,59+1,59+1,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,188044,30,ST,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,Right,0,€8.5M,"Dec 31, 2020 On Loan",365,66,79,76,68,76.0,375,83,78.0,72,63,79,404,83,83,88.0,75,75.0,372,74,81.0,75,74,68,313,54,33.0,78.0,72.0,76,70.0,77,35,20,22.0,55,1961,412,3 ★,4★,High,Low,2 ★,83,75,68,82,33,71,44,77+0,77+0,77+0,77+0,77+0,77+0,77+0,77+0,76+1,76+1,76+1,76+1,68+2,68+2,68+2,76+1,57+2,53+2,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,184431,33,CAM,Al Hilal 2019 ~ 2022,"5'4""",134lbs,Right,0,€9M,2019 ~ 2022,336,73,76,34,78,75.0,424,85,89.0,91,74,85,424,84,76,93.0,78,93.0,308,79,34.0,75,42,78,332,75,26.0,80.0,78.0,73,82.0,80,23,29,28.0,21,1925,404,4 ★,4★,High,Medium,2 ★,80,77,78,86,27,56,73,73+2,73+2,73+2,80+0,79+0,79+0,79+0,80+0,80+0,80+0,80+0,79+1,74+2,74+2,74+2,79+1,59+2,56+2,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,233796,22,CDM,Swansea City 2016 ~ 2021,"5'10""",152lbs,Right,13,€275K,2016 ~ 2021,242,44,42,58,62,36.0,259,54,41.0,46,57,61,282,54,59,59.0,55,55.0,277,57,60.0,64,58,38,257,61,57.0,31.0,54.0,54,48.0,168,55,58,55.0,42,1527,329,2 ★,2★,Medium,Medium,1 ★,57,44,54,57,57,60,7,50+2,50+2,50+2,51+0,51+0,51+0,51+0,51+0,53+2,53+2,53+2,53+2,56+2,56+2,56+2,53+2,56+2,58+2,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,234799,23,CDM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",150lbs,Right,8,€725K,2018 ~ 2021,249,49,37,61,68,34.0,280,64,44.0,45,61,66,324,66,66,61.0,62,69.0,280,61,34.0,81,61,43,294,66,60.0,55.0,64.0,49,58.0,185,58,61,66.0,52,1664,360,2 ★,3★,Low,Medium,1 ★,66,44,60,64,60,66,4,56+2,56+2,56+2,59+0,59+0,59+0,59+0,59+0,61+2,61+2,61+2,62+2,63+2,63+2,63+2,62+2,64+2,64+2,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65

In [7]:
data2.columns.values

array(['ID', 'Age', 'BP', 'Team & Contract', 'Height', 'Weight', 'foot',
       'Growth', 'Value', 'Contract', 'Attacking', 'Crossing',
       'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing',
       'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed',
       'Agility', 'Reactions', 'Balance', 'Power', 'Shot Power',
       'Jumping', 'Stamina', 'Strength', 'Long Shots', 'Mentality',
       'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking',
       'Standing Tackle', 'Sliding Tackle', 'Goalkeeping', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF',
       'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM',
       'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB',
       'GK', 'OVA'], dtype=object)

In [8]:
data2 = data2[['BP', 'Age', 'Height', 'Weight', 'foot', 'Growth', 'Value', 'Skill', 'Movement', 'Power', 'Mentality', 'Defending', 'Goalkeeping', 'Total Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS','DRI', 'DEF', 'PHY','OVA']]

In [9]:
data2.head().T

                  0       1       2       3       4
BP               CM      ST     CAM     CDM     CDM
Age              26      30      33      22      23
Height         5'9"    6'0"    5'4"   5'10"   5'11"
Weight       161lbs  159lbs  134lbs  152lbs  150lbs
foot          Right   Right   Right   Right   Right
Growth            1       0       0      13       8
Value         €525K   €8.5M     €9M   €275K   €725K
Skill           286     375     424     259     280
Movement        346     404     424     282     324
Power           306     372     308     277     280
Mentality       290     313     332     257     294
Defending       148      77      80     168     185
Goalkeeping      48      55      21      42      52
Total Stats    1682    1961    1925    1527    1664
W/F             4 ★     3 ★     4 ★     2 ★     2 ★
SM               2★      4★      4★      2★      3★
A/W            High    High    High  Medium     Low
D/W          Medium     Low  Medium  Medium  Medium
IR              1 ★     2 ★     2 ★     1 ★     1 ★
PAC              69      83      80      57      66
SHO              51      75      77      44      44
PAS              63      68      78      54      60
DRI              63      82      86      57      64
DEF              51      33      27      57      60
PHY              60      71      56      60      66
OVA              64      77      80      59      65

In [10]:
data2.describe(include = 'all')

,BP,Age,Height,Weight,foot,Growth,Value,Skill,Movement,Power,Mentality,Defending,Goalkeeping,Total Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,OVA
count,11701,11701.00000,11701,11701,11701,11701.000000,11701,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701,11701,11642,11642,11701,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000
unique,15,NaN,21,55,2,NaN,203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,3,3,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,CB,NaN,"6'0""",154lbs,Right,NaN,€1.1M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3 ★,2★,Medium,Medium,1 ★,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2170,NaN,1751,931,8828,NaN,342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7219,5127,7494,8350,10359,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,25.27049,NaN,NaN,NaN,5.534655,NaN,266.497222,322.617383,302.083326,261.704982,140.674558,77.726946,1629.786599,NaN,NaN,NaN,NaN,NaN,68.095206,55.046406,58.893257,64.223229,50.030254,64.817964,66.921972
std,NaN,4.95764,NaN,NaN,NaN,5.810903,NaN,76.835287,55.330054,49.697749,62.935298,61.599006,81.221525,260.766470,NaN,NaN,NaN,NaN,NaN,11.247282,13.851853,10.174939,9.818311,16.841283,9.757873,6.876081
min,NaN,16.00000,NaN,NaN,NaN,-1.000000,NaN,43.000000,113.000000,133.000000,55.000000,17.000000,12.000000,731.000000,NaN,NaN,NaN,NaN,NaN,26.000000,17.000000,25.000000,28.000000,12.000000,27.000000,38.000000
25%,NaN,21.00000,NaN,NaN,NaN,0.000000,NaN,232.000000,294.000000,271.000000,235.000000,83.000000,48.000000,1490.000000,NaN,NaN,NaN,NaN,NaN,62.000000,46.000000,52.000000,59.000000,35.000000,59.000000,62.000000
50%,NaN,25.00000,NaN,NaN,NaN,4.000000,NaN,279.000000,331.000000,308.000000,269.000000,156.000000,53.000000,1659.000000,NaN,NaN,NaN,NaN,NaN,69.000000,58.000000,59.000000,65.000000,53.000000,66.000000,67.000000
75%,NaN,29.00000,NaN,NaN,NaN,10.000000,NaN,319.000000,361.000000,339.000000,304.000000,194.000000,59.000000,1811.000000,NaN,NaN,NaN,NaN,NaN,76.000000,65.000000,66.000000,71.000000,64.000000,72.000000,72.000000
max,NaN,43.00000,NaN,NaN,NaN,26.000000,NaN,470.000000,464.000000,444.000000,414.000000,267.000000,439.000000,2304.000000,NaN,NaN,NaN,NaN,NaN,96.000000,93.000000,93.000000,95.000000,89.000000,93.000000,93.000000

In [11]:
data2.columns

Index(['BP', 'Age', 'Height', 'Weight', 'foot', 'Growth', 'Value', 'Skill',
       'Movement', 'Power', 'Mentality', 'Defending', 'Goalkeeping',
       'Total Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'OVA'],
      dtype='object')

In [12]:
data2.dtypes

BP             object
Age             int64
Height         object
Weight         object
foot           object
Growth          int64
Value          object
Skill           int64
Movement        int64
Power           int64
Mentality       int64
Defending       int64
Goalkeeping     int64
Total Stats     int64
W/F            object
SM             object
A/W            object
D/W            object
IR             object
PAC             int64
SHO             int64
PAS             int64
DRI             int64
DEF             int64
PHY             int64
OVA             int64
dtype: object

In [13]:
def feet_to_cm(height_str):
    feet, inches = map(int, height_str.replace('"', '').split("'"))
    total_inches = (feet * 12) + inches
    cm = total_inches * 2.54
    return cm

data2['Height'] = data2['Height'].apply(feet_to_cm)

In [14]:
data2.head()

,BP,Age,Height,Weight,foot,Growth,Value,Skill,Movement,Power,Mentality,Defending,Goalkeeping,Total Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,OVA
0,CM,26,175.26,161lbs,Right,1,€525K,286,346,306,290,148,48,1682,4 ★,2★,High,Medium,1 ★,69,51,63,63,51,60,64
1,ST,30,182.88,159lbs,Right,0,€8.5M,375,404,372,313,77,55,1961,3 ★,4★,High,Low,2 ★,83,75,68,82,33,71,77
2,CAM,33,162.56,134lbs,Right,0,€9M,424,424,308,332,80,21,1925,4 ★,4★,High,Medium,2 ★,80,77,78,86,27,56,80
3,CDM,22,177.80,152lbs,Right,13,€275K,259,282,277,257,168,42,1527,2 ★,2★,Medium,Medium,1 ★,57,44,54,57,57,60,59
4,CDM,23,180.34,150lbs,Right,8,€725K,280,324,280,294,185,52,1664,2 ★,3★,Low,Medium,1 ★,66,44,60,64,60,66,65

In [15]:
data2['Weight'] = data2['Weight'].str.replace('lbs', '').astype(float)

In [16]:
data2.head()

,BP,Age,Height,Weight,foot,Growth,Value,Skill,Movement,Power,Mentality,Defending,Goalkeeping,Total Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,OVA
0,CM,26,175.26,161.0,Right,1,€525K,286,346,306,290,148,48,1682,4 ★,2★,High,Medium,1 ★,69,51,63,63,51,60,64
1,ST,30,182.88,159.0,Right,0,€8.5M,375,404,372,313,77,55,1961,3 ★,4★,High,Low,2 ★,83,75,68,82,33,71,77
2,CAM,33,162.56,134.0,Right,0,€9M,424,424,308,332,80,21,1925,4 ★,4★,High,Medium,2 ★,80,77,78,86,27,56,80
3,CDM,22,177.80,152.0,Right,13,€275K,259,282,277,257,168,42,1527,2 ★,2★,Medium,Medium,1 ★,57,44,54,57,57,60,59
4,CDM,23,180.34,150.0,Right,8,€725K,280,324,280,294,185,52,1664,2 ★,3★,Low,Medium,1 ★,66,44,60,64,60,66,65

In [17]:
data2.dtypes

BP              object
Age              int64
Height         float64
Weight         float64
foot            object
Growth           int64
Value           object
Skill            int64
Movement         int64
Power            int64
Mentality        int64
Defending        int64
Goalkeeping      int64
Total Stats      int64
W/F             object
SM              object
A/W             object
D/W             object
IR              object
PAC              int64
SHO              int64
PAS              int64
DRI              int64
DEF              int64
PHY              int64
OVA              int64
dtype: object

In [18]:
def convert_value(value_str):
    value_str = value_str.replace('€', '') 
    if value_str.endswith('K'):
        return float(value_str[:-1]) * 1000  
    elif value_str.endswith('M'):
        return float(value_str[:-1]) * 1000000  
    else:
        return float(value_str)  

data2['Value'] = data2['Value'].apply(convert_value)

In [19]:
data2.head()

,BP,Age,Height,Weight,foot,Growth,Value,Skill,Movement,Power,Mentality,Defending,Goalkeeping,Total Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,OVA
0,CM,26,175.26,161.0,Right,1,525000.0,286,346,306,290,148,48,1682,4 ★,2★,High,Medium,1 ★,69,51,63,63,51,60,64
1,ST,30,182.88,159.0,Right,0,8500000.0,375,404,372,313,77,55,1961,3 ★,4★,High,Low,2 ★,83,75,68,82,33,71,77
2,CAM,33,162.56,134.0,Right,0,9000000.0,424,424,308,332,80,21,1925,4 ★,4★,High,Medium,2 ★,80,77,78,86,27,56,80
3,CDM,22,177.80,152.0,Right,13,275000.0,259,282,277,257,168,42,1527,2 ★,2★,Medium,Medium,1 ★,57,44,54,57,57,60,59
4,CDM,23,180.34,150.0,Right,8,725000.0,280,324,280,294,185,52,1664,2 ★,3★,Low,Medium,1 ★,66,44,60,64,60,66,65

In [20]:
data2.isna().sum()

BP              0
Age             0
Height          0
Weight          0
foot            0
Growth          0
Value           0
Skill           0
Movement        0
Power           0
Mentality       0
Defending       0
Goalkeeping     0
Total Stats     0
W/F             0
SM              0
A/W            59
D/W            59
IR              0
PAC             0
SHO             0
PAS             0
DRI             0
DEF             0
PHY             0
OVA             0
dtype: int64

In [21]:
data2["W/F"] = data2["W/F"].str.replace("★", "" )
data2["W/F"] = pd.to_numeric(data2["W/F"], errors='coerce')

In [22]:
data2.head()

,BP,Age,Height,Weight,foot,Growth,Value,Skill,Movement,Power,Mentality,Defending,Goalkeeping,Total Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,OVA
0,CM,26,175.26,161.0,Right,1,525000.0,286,346,306,290,148,48,1682,4,2★,High,Medium,1 ★,69,51,63,63,51,60,64
1,ST,30,182.88,159.0,Right,0,8500000.0,375,404,372,313,77,55,1961,3,4★,High,Low,2 ★,83,75,68,82,33,71,77
2,CAM,33,162.56,134.0,Right,0,9000000.0,424,424,308,332,80,21,1925,4,4★,High,Medium,2 ★,80,77,78,86,27,56,80
3,CDM,22,177.80,152.0,Right,13,275000.0,259,282,277,257,168,42,1527,2,2★,Medium,Medium,1 ★,57,44,54,57,57,60,59
4,CDM,23,180.34,150.0,Right,8,725000.0,280,324,280,294,185,52,1664,2,3★,Low,Medium,1 ★,66,44,60,64,60,66,65

In [23]:
data2["SM"] = data2["SM"].str.replace("★", "" )
data2["SM"] = pd.to_numeric(data2["SM"], errors='coerce')

In [24]:
data2["IR"] = data2["IR"].str.replace(" ★", "" )
data2["IR"] = pd.to_numeric(data2["IR"], errors='coerce')

In [25]:
data2.head()

,BP,Age,Height,Weight,foot,Growth,Value,Skill,Movement,Power,Mentality,Defending,Goalkeeping,Total Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,OVA
0,CM,26,175.26,161.0,Right,1,525000.0,286,346,306,290,148,48,1682,4,2,High,Medium,1,69,51,63,63,51,60,64
1,ST,30,182.88,159.0,Right,0,8500000.0,375,404,372,313,77,55,1961,3,4,High,Low,2,83,75,68,82,33,71,77
2,CAM,33,162.56,134.0,Right,0,9000000.0,424,424,308,332,80,21,1925,4,4,High,Medium,2,80,77,78,86,27,56,80
3,CDM,22,177.80,152.0,Right,13,275000.0,259,282,277,257,168,42,1527,2,2,Medium,Medium,1,57,44,54,57,57,60,59
4,CDM,23,180.34,150.0,Right,8,725000.0,280,324,280,294,185,52,1664,2,3,Low,Medium,1,66,44,60,64,60,66,65

In [26]:
data2["D/W"] = data2["D/W"].fillna('Medium') 
data2["A/W"] = data2["D/W"].fillna('Medium')

In [27]:
categorical = data2.select_dtypes('object')

In [28]:
numerical = data2._get_numeric_data()

In [29]:
categorical.head()

    BP   foot     A/W     D/W
0   CM  Right  Medium  Medium
1   ST  Right     Low     Low
2  CAM  Right  Medium  Medium
3  CDM  Right  Medium  Medium
4  CDM  Right  Medium  Medium

In [30]:
numerical.head()

,Age,Height,Weight,Growth,Value,Skill,Movement,Power,Mentality,Defending,Goalkeeping,Total Stats,W/F,SM,IR,PAC,SHO,PAS,DRI,DEF,PHY,OVA
0,26,175.26,161.0,1,525000.0,286,346,306,290,148,48,1682,4,2,1,69,51,63,63,51,60,64
1,30,182.88,159.0,0,8500000.0,375,404,372,313,77,55,1961,3,4,2,83,75,68,82,33,71,77
2,33,162.56,134.0,0,9000000.0,424,424,308,332,80,21,1925,4,4,2,80,77,78,86,27,56,80
3,22,177.80,152.0,13,275000.0,259,282,277,257,168,42,1527,2,2,1,57,44,54,57,57,60,59
4,23,180.34,150.0,8,725000.0,280,324,280,294,185,52,1664,2,3,1,66,44,60,64,60,66,65

In [31]:
categorical['A/W'].value_counts(dropna=False)

Medium    8409
High      2027
Low       1265
Name: A/W, dtype: int64

In [32]:
categorical['D/W'].value_counts(dropna=False)

Medium    8409
High      2027
Low       1265
Name: D/W, dtype: int64

In [45]:
X = numerical.drop(["OVA"], axis = 1)
y = data2["OVA"]

X.head()

,Age,Height,Weight,Growth,Value,Skill,Movement,Power,Mentality,Defending,Goalkeeping,Total Stats,W/F,SM,IR,PAC,SHO,PAS,DRI,DEF,PHY
0,26,175.26,161.0,1,525000.0,286,346,306,290,148,48,1682,4,2,1,69,51,63,63,51,60
1,30,182.88,159.0,0,8500000.0,375,404,372,313,77,55,1961,3,4,2,83,75,68,82,33,71
2,33,162.56,134.0,0,9000000.0,424,424,308,332,80,21,1925,4,4,2,80,77,78,86,27,56
3,22,177.80,152.0,13,275000.0,259,282,277,257,168,42,1527,2,2,1,57,44,54,57,57,60
4,23,180.34,150.0,8,725000.0,280,324,280,294,185,52,1664,2,3,1,66,44,60,64,60,66

In [49]:
scaler = MinMaxScaler()
scaled_df = scaler.fit_transform(X)
scaled_df = pd.DataFrame(scaled_df, columns=X.columns)

scaled_df.head()

,Age,Height,Weight,Growth,Value,Skill,Movement,Power,Mentality,Defending,Goalkeeping,Total Stats,W/F,SM,IR,PAC,SHO,PAS,DRI,DEF,PHY
0,0.370370,0.40,0.349206,0.074074,0.005833,0.569087,0.663818,0.556270,0.654596,0.524,0.084309,0.604577,0.75,0.25,0.00,0.614286,0.447368,0.558824,0.522388,0.506494,0.500000
1,0.518519,0.55,0.333333,0.037037,0.094444,0.777518,0.829060,0.768489,0.718663,0.240,0.100703,0.781945,0.50,0.75,0.25,0.814286,0.763158,0.632353,0.805970,0.272727,0.666667
2,0.629630,0.15,0.134921,0.037037,0.100000,0.892272,0.886040,0.562701,0.771588,0.252,0.021077,0.759059,0.75,0.75,0.25,0.771429,0.789474,0.779412,0.865672,0.194805,0.439394
3,0.222222,0.45,0.277778,0.518519,0.003056,0.505855,0.481481,0.463023,0.562674,0.604,0.070258,0.506039,0.25,0.25,0.00,0.442857,0.355263,0.426471,0.432836,0.584416,0.500000
4,0.259259,0.50,0.261905,0.333333,0.008056,0.555035,0.601140,0.472669,0.665738,0.672,0.093677,0.593134,0.25,0.50,0.00,0.571429,0.355263,0.514706,0.537313,0.623377,0.590909

In [ ]:
sns.boxplot(numerical_normalized)
plt.xticks(rotation=90)
plt.show()

In [ ]:
encoder = OneHotEncoder(drop='first').fit(categorical)

cols = encoder.get_feature_names_out(input_features=categorical.columns)
categorical_encode = pd.DataFrame(encoder.transform(categorical).toarray(),columns=cols)
categorical_encode.head().T

In [ ]:
data3 = pd.concat([numerical_scaled, categorical_encode], axis=1)

In [ ]:
data3.head().T