In [1]:
import pandas as pd
df = pd.read_csv("fifa21_train.csv")
import functions2
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import numpy as np

In [2]:
df = functions2.only_clean(df)

/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['Height'] = data2['Height'].apply(feet_to_cm)
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['Weight'] = data2['Weight'].str.replace('lbs', '').astype(float)
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['Value'] = data2['Value'].apply(convert_value)
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["W/F"] = data2["W/F"].str.replace("★", "" )
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["W/F"] = pd.to_numeric(data2["W/F"], errors='coerce')
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["SM"] = data2["SM"].str.replace("★", "" )
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["SM"] = pd.to_numeric(data2["SM"], errors='coerce')
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["IR"] = data2["IR"].str.replace(" ★", "" )
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["IR"] = pd.to_numeric(data2["IR"], errors='coerce')
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["D/W"] = data2["D/W"].fillna('Medium')
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["A/W"] = data2["D/W"].fillna('Medium')

In [3]:
df.head()

,BP,Age,Height,Weight,foot,Growth,Value,Skill,Movement,Power,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,OVA
0,CM,26,175.26,161.0,Right,1,525000.0,286,346,306,...,Medium,Medium,1,69,51,63,63,51,60,64
1,ST,30,182.88,159.0,Right,0,8500000.0,375,404,372,...,Low,Low,2,83,75,68,82,33,71,77
2,CAM,33,162.56,134.0,Right,0,9000000.0,424,424,308,...,Medium,Medium,2,80,77,78,86,27,56,80
3,CDM,22,177.80,152.0,Right,13,275000.0,259,282,277,...,Medium,Medium,1,57,44,54,57,57,60,59
4,CDM,23,180.34,150.0,Right,8,725000.0,280,324,280,...,Medium,Medium,1,66,44,60,64,60,66,65

In [4]:
y, X = functions2.min_max_encode(df,'OVA')

In [5]:
X.head()

,Age,Height,Weight,Growth,Value,Skill,Movement,Power,Mentality,Defending,...,BP_RB,BP_RM,BP_RW,BP_RWB,BP_ST,foot_Right,A/W_Low,A/W_Medium,D/W_Low,D/W_Medium
0,0.370370,0.40,0.349206,0.074074,0.005833,0.569087,0.663818,0.556270,0.654596,0.524,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
1,0.518519,0.55,0.333333,0.037037,0.094444,0.777518,0.829060,0.768489,0.718663,0.240,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0
2,0.629630,0.15,0.134921,0.037037,0.100000,0.892272,0.886040,0.562701,0.771588,0.252,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
3,0.222222,0.45,0.277778,0.518519,0.003056,0.505855,0.481481,0.463023,0.562674,0.604,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,0.259259,0.50,0.261905,0.333333,0.008056,0.555035,0.601140,0.472669,0.665738,0.672,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0

In [6]:
lm = linear_model.LinearRegression()

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [8]:
lm.fit(X_train,y_train)

LinearRegression()

In [9]:
predictions = lm.predict(X_train)
r2_score(y_train, predictions)

0.8737403088407444

In [10]:
predictions_test = lm.predict(X_test)
r2_score(y_test, predictions_test)

0.8618044222454948

In [11]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,predictions_test)
mse

6.4578571291202564

In [12]:
rmse = np.sqrt(mean_squared_error(y_test, predictions_test))
rmse

2.5412314198278474

In [13]:
df_to_validate = pd.read_csv('fifa21_validate.csv')

In [14]:
df_to_validate.head()

,ID,Name,Age,Nationality,Club,BP,Position,Team & Contract,Height,Weight,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,219461,E. Palmer-Brown,23,United States,FK Austria Wien,CB,CB,"FK Austria Wien Jun 30, 2021 On Loan","6'2""",194lbs,...,61+2,61+2,59+2,61+2,67+2,67+2,67+2,61+2,16+2,67
1,221896,D. Avdijaj,22,Kosovo,Heart of Midlothian,CAM,LM CAM,Heart of Midlothian 2020 ~ 2020,"5'8""",154lbs,...,47+2,47+2,49+2,45+2,38+2,38+2,38+2,45+2,17+2,68
2,247428,D. Ochoa,19,United States,Real Salt Lake,GK,GK,Real Salt Lake 2018 ~ 2020,"6'2""",176lbs,...,18+2,18+2,16+2,16+2,18+2,18+2,18+2,16+2,53+2,54
3,255120,N. Kenneh,16,England,Leeds United,CDM,CB CDM RB,Leeds United 2020 ~ 2022,"6'3""",170lbs,...,54+2,54+2,53+2,53+2,54+2,54+2,54+2,53+2,11+2,55
4,215556,E. Fernandes,24,Switzerland,1. FSV Mainz 05,CDM,CM CDM,1. FSV Mainz 05 2019 ~ 2023,"6'2""",170lbs,...,72+2,72+2,70+2,69+2,68+2,68+2,68+2,69+2,18+2,70

# Starting on Making Predictions with the validation data

In [15]:
df_to_validate = functions2.only_clean(df_to_validate)
df_to_validate.head()

/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['Height'] = data2['Height'].apply(feet_to_cm)
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['Weight'] = data2['Weight'].str.replace('lbs', '').astype(float)
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['Value'] = data2['Value'].apply(convert_value)
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["W/F"] = data2["W/F"].str.replace("★", "" )
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["W/F"] = pd.to_numeric(data2["W/F"], errors='coerce')
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["SM"] = data2["SM"].str.replace("★", "" )
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["SM"] = pd.to_numeric(data2["SM"], errors='coerce')
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["IR"] = data2["IR"].str.replace(" ★", "" )
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["IR"] = pd.to_numeric(data2["IR"], errors='coerce')
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["D/W"] = data2["D/W"].fillna('Medium')
/Users/v.adragna/Desktop/IH-Labs/Week-2/Fifa Project/functions2.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["A/W"] = data2["D/W"].fillna('Medium')

,BP,Age,Height,Weight,foot,Growth,Value,Skill,Movement,Power,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,OVA
0,CB,23,187.96,194.0,Right,7,975000.0,228,303,288,...,High,High,1,64,30,50,50,66,74,67
1,CAM,22,172.72,154.0,Right,5,1200000.0,330,375,323,...,Low,Low,1,74,67,62,74,24,57,68
2,GK,19,187.96,176.0,Right,17,120000.0,52,165,171,...,Medium,Medium,1,56,52,53,55,26,53,54
3,CDM,16,190.50,170.0,Right,23,160000.0,224,275,242,...,Medium,Medium,1,58,34,47,52,53,59,55
4,CDM,24,187.96,170.0,Right,5,2300000.0,327,320,337,...,Medium,Medium,1,67,62,68,70,69,71,70

In [16]:
y2, X2 = functions2.min_max_encode(df_to_validate,'OVA')

In [17]:
X2.head()

,Age,Height,Weight,Growth,Value,Skill,Movement,Power,Mentality,Defending,...,BP_RB,BP_RM,BP_RW,BP_RWB,BP_ST,foot_Right,A/W_Low,A/W_Medium,D/W_Low,D/W_Medium
0,0.225806,0.666667,0.694444,0.28,0.012500,0.463158,0.535503,0.541219,0.517906,0.708502,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.193548,0.266667,0.324074,0.20,0.015385,0.731579,0.748521,0.666667,0.628099,0.145749,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,0.096774,0.666667,0.527778,0.68,0.001538,0.000000,0.127219,0.121864,0.049587,0.008097,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
3,0.000000,0.733333,0.472222,0.92,0.002051,0.452632,0.452663,0.376344,0.473829,0.542510,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,0.258065,0.666667,0.472222,0.20,0.029487,0.723684,0.585799,0.716846,0.705234,0.753036,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0

In [18]:
predictions1 = lm.predict(X2)

In [19]:
predictions1

array([64.81504415, 65.72033923, 54.15857186, ..., 73.52634966,
       64.54124224, 58.87107622])

In [20]:
from sklearn.metrics import mean_absolute_error, r2_score

In [21]:
predictions2 = lm.predict(X2)
r2_score(y2, predictions2)

0.8440814103777935

In [22]:
mse=mean_squared_error(y2, predictions2)
mse

7.135065582884674

In [23]:
rmse2 = np.sqrt(mean_squared_error(y2, predictions2))
rmse2

2.671154353998412

In [24]:
mae2 = mean_absolute_error(y2, predictions2)
mae2

2.0115046799397587

In [25]:
y.mean()

66.92197248098454

In [ ]:
# The model has an accurancy on about 3%